### ISSUE TITLE
[JOSS] Confirmation of authorship

### ISSUE THREAD

**Issue by ianfhunter** [ulissigroup/amptorch#114] opened 2023-05-02 14:16 UTC
Hi, I'm starting to go through the JOSS review checklist (https://github.com/openjournals/joss-reviews/issues/5035).

First thing I notice is that I don't see the submitter's username (@ajmedford) in any commits to this repository.
There are 8 contributors, but 12 authors credited on the paper. 

Also if you could confirm for me that @mshuaibii and @nicoleyghu are intended to be equal contributors (@mshuaibii appears to have an order of magnitude more contributions than @nicoleyghu - 480 commits vs 16, as well as those commits being a bit more substantial too.

non-code contributions are fine as per the JOSS authorship guidelines:
> Purely financial (such as being named on an award) and organizational (such as general supervision of a research group) contributions are not considered sufficient for co-authorship of JOSS submissions, but active project direction and other forms of non-code contributions are. The authors themselves assume responsibility for deciding who should be credited with co-authorship, and co-authors must always agree to be listed. In addition, co-authors agree to be accountable for all aspects of the work, and to notify JOSS if any retraction or correction of mistakes are needed after publication.

but, I feel it would be remiss of me to not confirm that it is as intended.

**Comment by ajmedford** [comment] 2023-05-02 14:31
@ianfhunter good questions. I am the PI of Nicole's research group, and unfortunately have very little time to write code anymore. However, I have been involved with "active project direction" by consulting with @nicoleyghu @mshuaibii @zulissi and others. Similarly, @aapeterson and @zulissi are also PIs, but have been involved with directing the structure of the code (@aapeterson was the architect of the original AMP package). @mshuaibii wrote the original port of AMP to PyTorch, and has written a lot more code, while @nicoleyghu was more involved with the implementation and testing of the intellectually new features (UQ, GMP, etc.), and wrote the text part of the "paper", so we felt that the equal contributions was appropriate. We have also had contributions from one additional person since the review started, and we plan to add him to the author list. We have consulted with all co-authors, and I think everyone is on the same page, but I'm open to adjusting if any editors or other co-authors have issues.

**Comment by ianfhunter** [comment] 2023-05-03 14:05
👍 Thanks AJ. That's fine by me, just checking

**Comment by ajmedford** [comment] 2023-05-08 14:21
@ianfhunter  - @nicoleyghu has now fixed this issue, which was apparently caused by a version conflict with numpy. Can you give it another try and see if you still have issues?

**Closed** 2023-05-17 18:09 UTC
